/**
 * S&P 500 companies for autocomplete.
 * Source: https://github.com/datasets/s-and-p-500-companies
 * Format: { symbol, name }
 */
export const STOCKS: { symbol: string; name: string }[] = [
  { symbol: "MMM", name: "3M" },
  { symbol: "AOS", name: "A. O. Smith" },
  { symbol: "ABT", name: "Abbott Laboratories" },
  { symbol: "ABBV", name: "AbbVie" },
  { symbol: "ACN", name: "Accenture" },
  { symbol: "ADBE", name: "Adobe Inc." },
  { symbol: "AMD", name: "Advanced Micro Devices" },
  { symbol: "AES", name: "AES Corporation" },
  { symbol: "AFL", name: "Aflac" },
  { symbol: "A", name: "Agilent Technologies" },
  { symbol: "APD", name: "Air Products" },
  { symbol: "ABNB", name: "Airbnb" },
  { symbol: "AKAM", name: "Akamai Technologies" },
  { symbol: "ALB", name: "Albemarle Corporation" },
  { symbol: "ARE", name: "Alexandria Real Estate Equities" },
  { symbol: "ALGN", name: "Align Technology" },
  { symbol: "ALLE", name: "Allegion" },
  { symbol: "LNT", name: "Alliant Energy" },
  { symbol: "ALL", name: "Allstate" },
  { symbol: "GOOGL", name: "Alphabet Inc. (Class A)" },
  { symbol: "GOOG", name: "Alphabet Inc. (Class C)" },
  { symbol: "MO", name: "Altria" },
  { symbol: "AMZN", name: "Amazon" },
  { symbol: "AMCR", name: "Amcor" },
  { symbol: "AEE", name: "Ameren" },
  { symbol: "AEP", name: "American Electric Power" },
  { symbol: "AXP", name: "American Express" },
  { symbol: "AIG", name: "American International Group" },
  { symbol: "AMT", name: "American Tower" },
  { symbol: "AWK", name: "American Water Works" },
  { symbol: "AMP", name: "Ameriprise Financial" },
  { symbol: "AME", name: "Ametek" },
  { symbol: "AMGN", name: "Amgen" },
  { symbol: "APH", name: "Amphenol" },
  { symbol: "ADI", name: "Analog Devices" },
  { symbol: "AON", name: "Aon plc" },
  { symbol: "APA", name: "APA Corporation" },
  { symbol: "APO", name: "Apollo Global Management" },
  { symbol: "AAPL", name: "Apple Inc." },
  { symbol: "AMAT", name: "Applied Materials" },
  { symbol: "APP", name: "AppLovin" },
  { symbol: "APTV", name: "Aptiv" },
  { symbol: "ACGL", name: "Arch Capital Group" },
  { symbol: "ADM", name: "Archer Daniels Midland" },
  { symbol: "ARES", name: "Ares Management" },
  { symbol: "ANET", name: "Arista Networks" },
  { symbol: "AJG", name: "Arthur J. Gallagher & Co." },
  { symbol: "AIZ", name: "Assurant" },
  { symbol: "T", name: "AT&T" },
  { symbol: "ATO", name: "Atmos Energy" },
  { symbol: "ADSK", name: "Autodesk" },
  { symbol: "ADP", name: "Automatic Data Processing" },
  { symbol: "AZO", name: "AutoZone" },
  { symbol: "AVB", name: "AvalonBay Communities" },
  { symbol: "AVY", name: "Avery Dennison" },
  { symbol: "AXON", name: "Axon Enterprise" },
  { symbol: "BKR", name: "Baker Hughes" },
  { symbol: "BALL", name: "Ball Corporation" },
  { symbol: "BAC", name: "Bank of America" },
  { symbol: "BAX", name: "Baxter International" },
  { symbol: "BDX", name: "Becton Dickinson" },
  { symbol: "BRK.B", name: "Berkshire Hathaway" },
  { symbol: "BBY", name: "Best Buy" },
  { symbol: "TECH", name: "Bio-Techne" },
  { symbol: "BIIB", name: "Biogen" },
  { symbol: "BLK", name: "BlackRock" },
  { symbol: "BX", name: "Blackstone Inc." },
  { symbol: "XYZ", name: "Block, Inc." },
  { symbol: "BK", name: "BNY Mellon" },
  { symbol: "BA", name: "Boeing" },
  { symbol: "BKNG", name: "Booking Holdings" },
  { symbol: "BSX", name: "Boston Scientific" },
  { symbol: "BMY", name: "Bristol Myers Squibb" },
  { symbol: "AVGO", name: "Broadcom" },
  { symbol: "BR", name: "Broadridge Financial Solutions" },
  { symbol: "BRO", name: "Brown & Brown" },
  { symbol: "BF.B", name: "Brown–Forman" },
  { symbol: "BLDR", name: "Builders FirstSource" },
  { symbol: "BG", name: "Bunge Global" },
  { symbol: "BXP", name: "BXP, Inc." },
  { symbol: "CHRW", name: "C.H. Robinson" },
  { symbol: "CDNS", name: "Cadence Design Systems" },
  { symbol: "CPT", name: "Camden Property Trust" },
  { symbol: "CPB", name: "Campbell's Company (The)" },
  { symbol: "COF", name: "Capital One" },
  { symbol: "CAH", name: "Cardinal Health" },
  { symbol: "CCL", name: "Carnival" },
  { symbol: "CARR", name: "Carrier Global" },
  { symbol: "CVNA", name: "Carvana" },
  { symbol: "CAT", name: "Caterpillar Inc." },
  { symbol: "CBOE", name: "Cboe Global Markets" },
  { symbol: "CBRE", name: "CBRE Group" },
  { symbol: "CDW", name: "CDW Corporation" },
  { symbol: "COR", name: "Cencora" },
  { symbol: "CNC", name: "Centene Corporation" },
  { symbol: "CNP", name: "CenterPoint Energy" },
  { symbol: "CF", name: "CF Industries" },
  { symbol: "CRL", name: "Charles River Laboratories" },
  { symbol: "SCHW", name: "Charles Schwab Corporation" },
  { symbol: "CHTR", name: "Charter Communications" },
  { symbol: "CVX", name: "Chevron Corporation" },
  { symbol: "CMG", name: "Chipotle Mexican Grill" },
  { symbol: "CB", name: "Chubb Limited" },
  { symbol: "CHD", name: "Church & Dwight" },
  { symbol: "CIEN", name: "Ciena" },
  { symbol: "CI", name: "Cigna" },
  { symbol: "CINF", name: "Cincinnati Financial" },
  { symbol: "CTAS", name: "Cintas" },
  { symbol: "CSCO", name: "Cisco" },
  { symbol: "C", name: "Citigroup" },
  { symbol: "CFG", name: "Citizens Financial Group" },
  { symbol: "CLX", name: "Clorox" },
  { symbol: "CME", name: "CME Group" },
  { symbol: "CMS", name: "CMS Energy" },
  { symbol: "KO", name: "Coca-Cola Company (The)" },
  { symbol: "CTSH", name: "Cognizant" },
  { symbol: "COIN", name: "Coinbase" },
  { symbol: "CL", name: "Colgate-Palmolive" },
  { symbol: "CMCSA", name: "Comcast" },
  { symbol: "FIX", name: "Comfort Systems USA" },
  { symbol: "CAG", name: "Conagra Brands" },
  { symbol: "COP", name: "ConocoPhillips" },
  { symbol: "ED", name: "Consolidated Edison" },
  { symbol: "STZ", name: "Constellation Brands" },
  { symbol: "CEG", name: "Constellation Energy" },
  { symbol: "COO", name: "Cooper Companies (The)" },
  { symbol: "CPRT", name: "Copart" },
  { symbol: "GLW", name: "Corning Inc." },
  { symbol: "CPAY", name: "Corpay" },
  { symbol: "CTVA", name: "Corteva" },
  { symbol: "CSGP", name: "CoStar Group" },
  { symbol: "COST", name: "Costco" },
  { symbol: "CTRA", name: "Coterra" },
  { symbol: "CRH", name: "CRH plc" },
  { symbol: "CRWD", name: "CrowdStrike" },
  { symbol: "CCI", name: "Crown Castle" },
  { symbol: "CSX", name: "CSX Corporation" },
  { symbol: "CMI", name: "Cummins" },
  { symbol: "CVS", name: "CVS Health" },
  { symbol: "DHR", name: "Danaher Corporation" },
  { symbol: "DRI", name: "Darden Restaurants" },
  { symbol: "DDOG", name: "Datadog" },
  { symbol: "DVA", name: "DaVita" },
  { symbol: "DECK", name: "Deckers Brands" },
  { symbol: "DE", name: "Deere & Company" },
  { symbol: "DELL", name: "Dell Technologies" },
  { symbol: "DAL", name: "Delta Air Lines" },
  { symbol: "DVN", name: "Devon Energy" },
  { symbol: "DXCM", name: "Dexcom" },
  { symbol: "FANG", name: "Diamondback Energy" },
  { symbol: "DLR", name: "Digital Realty" },
  { symbol: "DG", name: "Dollar General" },
  { symbol: "DLTR", name: "Dollar Tree" },
  { symbol: "D", name: "Dominion Energy" },
  { symbol: "DPZ", name: "Domino's" },
  { symbol: "DASH", name: "DoorDash" },
  { symbol: "DOV", name: "Dover Corporation" },
  { symbol: "DOW", name: "Dow Inc." },
  { symbol: "DHI", name: "D. R. Horton" },
  { symbol: "DTE", name: "DTE Energy" },
  { symbol: "DUK", name: "Duke Energy" },
  { symbol: "DD", name: "DuPont" },
  { symbol: "ETN", name: "Eaton Corporation" },
  { symbol: "EBAY", name: "eBay Inc." },
  { symbol: "ECL", name: "Ecolab" },
  { symbol: "EIX", name: "Edison International" },
  { symbol: "EW", name: "Edwards Lifesciences" },
  { symbol: "EA", name: "Electronic Arts" },
  { symbol: "ELV", name: "Elevance Health" },
  { symbol: "EME", name: "Emcor" },
  { symbol: "EMR", name: "Emerson Electric" },
  { symbol: "ETR", name: "Entergy" },
  { symbol: "EOG", name: "EOG Resources" },
  { symbol: "EPAM", name: "EPAM Systems" },
  { symbol: "EQT", name: "EQT Corporation" },
  { symbol: "EFX", name: "Equifax" },
  { symbol: "EQIX", name: "Equinix" },
  { symbol: "EQR", name: "Equity Residential" },
  { symbol: "ERIE", name: "Erie Indemnity" },
  { symbol: "ESS", name: "Essex Property Trust" },
  { symbol: "EL", name: "Estée Lauder Companies (The)" },
  { symbol: "EG", name: "Everest Group" },
  { symbol: "EVRG", name: "Evergy" },
  { symbol: "ES", name: "Eversource Energy" },
  { symbol: "EXC", name: "Exelon" },
  { symbol: "EXE", name: "Expand Energy" },
  { symbol: "EXPE", name: "Expedia Group" },
  { symbol: "EXPD", name: "Expeditors International" },
  { symbol: "EXR", name: "Extra Space Storage" },
  { symbol: "XOM", name: "ExxonMobil" },
  { symbol: "FFIV", name: "F5, Inc." },
  { symbol: "FDS", name: "FactSet" },
  { symbol: "FICO", name: "Fair Isaac" },
  { symbol: "FAST", name: "Fastenal" },
  { symbol: "FRT", name: "Federal Realty Investment Trust" },
  { symbol: "FDX", name: "FedEx" },
  { symbol: "FIS", name: "Fidelity National Information Services" },
  { symbol: "FITB", name: "Fifth Third Bancorp" },
  { symbol: "FSLR", name: "First Solar" },
  { symbol: "FE", name: "FirstEnergy" },
  { symbol: "FISV", name: "Fiserv" },
  { symbol: "F", name: "Ford Motor Company" },
  { symbol: "FTNT", name: "Fortinet" },
  { symbol: "FTV", name: "Fortive" },
  { symbol: "FOXA", name: "Fox Corporation (Class A)" },
  { symbol: "FOX", name: "Fox Corporation (Class B)" },
  { symbol: "BEN", name: "Franklin Resources" },
  { symbol: "FCX", name: "Freeport-McMoRan" },
  { symbol: "GRMN", name: "Garmin" },
  { symbol: "IT", name: "Gartner" },
  { symbol: "GE", name: "GE Aerospace" },
  { symbol: "GEHC", name: "GE HealthCare" },
  { symbol: "GEV", name: "GE Vernova" },
  { symbol: "GEN", name: "Gen Digital" },
  { symbol: "GNRC", name: "Generac" },
  { symbol: "GD", name: "General Dynamics" },
  { symbol: "GIS", name: "General Mills" },
  { symbol: "GM", name: "General Motors" },
  { symbol: "GPC", name: "Genuine Parts Company" },
  { symbol: "GILD", name: "Gilead Sciences" },
  { symbol: "GPN", name: "Global Payments" },
  { symbol: "GL", name: "Globe Life" },
  { symbol: "GDDY", name: "GoDaddy" },
  { symbol: "GS", name: "Goldman Sachs" },
  { symbol: "HAL", name: "Halliburton" },
  { symbol: "HIG", name: "Hartford (The)" },
  { symbol: "HAS", name: "Hasbro" },
  { symbol: "HCA", name: "HCA Healthcare" },
  { symbol: "DOC", name: "Healthpeak Properties,Real Estate" },
  { symbol: "HSIC", name: "Henry Schein" },
  { symbol: "HSY", name: "Hershey Company (The)" },
  { symbol: "HPE", name: "Hewlett Packard Enterprise" },
  { symbol: "HLT", name: "Hilton Worldwide" },
  { symbol: "HOLX", name: "Hologic" },
  { symbol: "HD", name: "Home Depot (The)" },
  { symbol: "HON", name: "Honeywell" },
  { symbol: "HRL", name: "Hormel Foods" },
  { symbol: "HST", name: "Host Hotels & Resorts" },
  { symbol: "HWM", name: "Howmet Aerospace" },
  { symbol: "HPQ", name: "HP Inc." },
  { symbol: "HUBB", name: "Hubbell Incorporated" },
  { symbol: "HUM", name: "Humana" },
  { symbol: "HBAN", name: "Huntington Bancshares" },
  { symbol: "HII", name: "Huntington Ingalls Industries" },
  { symbol: "IBM", name: "IBM" },
  { symbol: "IEX", name: "IDEX Corporation" },
  { symbol: "IDXX", name: "Idexx Laboratories" },
  { symbol: "ITW", name: "Illinois Tool Works" },
  { symbol: "INCY", name: "Incyte" },
  { symbol: "IR", name: "Ingersoll Rand" },
  { symbol: "PODD", name: "Insulet Corporation" },
  { symbol: "INTC", name: "Intel" },
  { symbol: "IBKR", name: "Interactive Brokers" },
  { symbol: "ICE", name: "Intercontinental Exchange" },
  { symbol: "IFF", name: "International Flavors & Fragrances" },
  { symbol: "IP", name: "International Paper" },
  { symbol: "INTU", name: "Intuit" },
  { symbol: "ISRG", name: "Intuitive Surgical" },
  { symbol: "IVZ", name: "Invesco" },
  { symbol: "INVH", name: "Invitation Homes" },
  { symbol: "IQV", name: "IQVIA" },
  { symbol: "IRM", name: "Iron Mountain" },
  { symbol: "JBHT", name: "J.B. Hunt" },
  { symbol: "JBL", name: "Jabil" },
  { symbol: "JKHY", name: "Jack Henry & Associates" },
  { symbol: "J", name: "Jacobs Solutions" },
  { symbol: "JNJ", name: "Johnson & Johnson" },
  { symbol: "JCI", name: "Johnson Controls" },
  { symbol: "JPM", name: "JPMorgan Chase" },
  { symbol: "KVUE", name: "Kenvue" },
  { symbol: "KDP", name: "Keurig Dr Pepper" },
  { symbol: "KEY", name: "KeyCorp" },
  { symbol: "KEYS", name: "Keysight Technologies" },
  { symbol: "KMB", name: "Kimberly-Clark" },
  { symbol: "KIM", name: "Kimco Realty" },
  { symbol: "KMI", name: "Kinder Morgan" },
  { symbol: "KKR", name: "KKR & Co." },
  { symbol: "KLAC", name: "KLA Corporation" },
  { symbol: "KHC", name: "Kraft Heinz" },
  { symbol: "KR", name: "Kroger" },
  { symbol: "LHX", name: "L3Harris" },
  { symbol: "LH", name: "Labcorp" },
  { symbol: "LRCX", name: "Lam Research" },
  { symbol: "LW", name: "Lamb Weston" },
  { symbol: "LVS", name: "Las Vegas Sands" },
  { symbol: "LDOS", name: "Leidos" },
  { symbol: "LEN", name: "Lennar" },
  { symbol: "LII", name: "Lennox International" },
  { symbol: "LLY", name: "Lilly (Eli)" },
  { symbol: "LIN", name: "Linde plc" },
  { symbol: "LYV", name: "Live Nation Entertainment" },
  { symbol: "LMT", name: "Lockheed Martin" },
  { symbol: "L", name: "Loews Corporation" },
  { symbol: "LOW", name: "Lowe's" },
  { symbol: "LULU", name: "Lululemon Athletica" },
  { symbol: "LYB", name: "LyondellBasell" },
  { symbol: "MTB", name: "M&T Bank" },
  { symbol: "MPC", name: "Marathon Petroleum" },
  { symbol: "MAR", name: "Marriott International" },
  { symbol: "MRSH", name: "Marsh McLennan" },
  { symbol: "MLM", name: "Martin Marietta Materials" },
  { symbol: "MAS", name: "Masco" },
  { symbol: "MA", name: "Mastercard" },
  { symbol: "MTCH", name: "Match Group" },
  { symbol: "MKC", name: "McCormick & Company" },
  { symbol: "MCD", name: "McDonald's" },
  { symbol: "MCK", name: "McKesson Corporation" },
  { symbol: "MDT", name: "Medtronic" },
  { symbol: "MRK", name: "Merck & Co." },
  { symbol: "META", name: "Meta Platforms" },
  { symbol: "MET", name: "MetLife" },
  { symbol: "MTD", name: "Mettler Toledo" },
  { symbol: "MGM", name: "MGM Resorts" },
  { symbol: "MCHP", name: "Microchip Technology" },
  { symbol: "MU", name: "Micron Technology" },
  { symbol: "MSFT", name: "Microsoft" },
  { symbol: "MAA", name: "Mid-America Apartment Communities" },
  { symbol: "MRNA", name: "Moderna" },
  { symbol: "MOH", name: "Molina Healthcare" },
  { symbol: "TAP", name: "Molson Coors Beverage Company" },
  { symbol: "MDLZ", name: "Mondelez International" },
  { symbol: "MPWR", name: "Monolithic Power Systems" },
  { symbol: "MNST", name: "Monster Beverage" },
  { symbol: "MCO", name: "Moody's Corporation" },
  { symbol: "MS", name: "Morgan Stanley" },
  { symbol: "MOS", name: "Mosaic Company (The)" },
  { symbol: "MSI", name: "Motorola Solutions" },
  { symbol: "MSCI", name: "MSCI Inc." },
  { symbol: "NDAQ", name: "Nasdaq, Inc." },
  { symbol: "NTAP", name: "NetApp" },
  { symbol: "NFLX", name: "Netflix" },
  { symbol: "NEM", name: "Newmont" },
  { symbol: "NWSA", name: "News Corp (Class A)" },
  { symbol: "NWS", name: "News Corp (Class B)" },
  { symbol: "NEE", name: "NextEra Energy" },
  { symbol: "NKE", name: "Nike, Inc." },
  { symbol: "NI", name: "NiSource" },
  { symbol: "NDSN", name: "Nordson Corporation" },
  { symbol: "NSC", name: "Norfolk Southern" },
  { symbol: "NTRS", name: "Northern Trust" },
  { symbol: "NOC", name: "Northrop Grumman" },
  { symbol: "NCLH", name: "Norwegian Cruise Line Holdings" },
  { symbol: "NRG", name: "NRG Energy" },
  { symbol: "NUE", name: "Nucor" },
  { symbol: "NVDA", name: "Nvidia" },
  { symbol: "NVR", name: "NVR, Inc." },
  { symbol: "NXPI", name: "NXP Semiconductors" },
  { symbol: "ORLY", name: "O’Reilly Automotive" },
  { symbol: "OXY", name: "Occidental Petroleum" },
  { symbol: "ODFL", name: "Old Dominion" },
  { symbol: "OMC", name: "Omnicom Group" },
  { symbol: "ON", name: "ON Semiconductor" },
  { symbol: "OKE", name: "Oneok" },
  { symbol: "ORCL", name: "Oracle Corporation" },
  { symbol: "OTIS", name: "Otis Worldwide" },
  { symbol: "PCAR", name: "Paccar" },
  { symbol: "PKG", name: "Packaging Corporation of America" },
  { symbol: "PLTR", name: "Palantir Technologies" },
  { symbol: "PANW", name: "Palo Alto Networks" },
  { symbol: "PSKY", name: "Paramount Skydance Corporation" },
  { symbol: "PH", name: "Parker Hannifin" },
  { symbol: "PAYX", name: "Paychex" },
  { symbol: "PAYC", name: "Paycom" },
  { symbol: "PYPL", name: "PayPal" },
  { symbol: "PNR", name: "Pentair" },
  { symbol: "PEP", name: "PepsiCo" },
  { symbol: "PFE", name: "Pfizer" },
  { symbol: "PCG", name: "PG&E Corporation" },
  { symbol: "PM", name: "Philip Morris International" },
  { symbol: "PSX", name: "Phillips 66" },
  { symbol: "PNW", name: "Pinnacle West Capital" },
  { symbol: "PNC", name: "PNC Financial Services" },
  { symbol: "POOL", name: "Pool Corporation" },
  { symbol: "PPG", name: "PPG Industries" },
  { symbol: "PPL", name: "PPL Corporation" },
  { symbol: "PFG", name: "Principal Financial Group" },
  { symbol: "PG", name: "Procter & Gamble" },
  { symbol: "PGR", name: "Progressive Corporation" },
  { symbol: "PLD", name: "Prologis" },
  { symbol: "PRU", name: "Prudential Financial" },
  { symbol: "PEG", name: "Public Service Enterprise Group" },
  { symbol: "PTC", name: "PTC Inc." },
  { symbol: "PSA", name: "Public Storage" },
  { symbol: "PHM", name: "PulteGroup" },
  { symbol: "PWR", name: "Quanta Services" },
  { symbol: "QCOM", name: "Qualcomm" },
  { symbol: "DGX", name: "Quest Diagnostics" },
  { symbol: "Q", name: "Qnity Electronics" },
  { symbol: "RL", name: "Ralph Lauren Corporation" },
  { symbol: "RJF", name: "Raymond James Financial" },
  { symbol: "RTX", name: "RTX Corporation" },
  { symbol: "O", name: "Realty Income" },
  { symbol: "REG", name: "Regency Centers" },
  { symbol: "REGN", name: "Regeneron Pharmaceuticals" },
  { symbol: "RF", name: "Regions Financial Corporation" },
  { symbol: "RSG", name: "Republic Services" },
  { symbol: "RMD", name: "ResMed" },
  { symbol: "RVTY", name: "Revvity" },
  { symbol: "HOOD", name: "Robinhood Markets" },
  { symbol: "ROK", name: "Rockwell Automation" },
  { symbol: "ROL", name: "Rollins, Inc." },
  { symbol: "ROP", name: "Roper Technologies" },
  { symbol: "ROST", name: "Ross Stores" },
  { symbol: "RCL", name: "Royal Caribbean Group" },
  { symbol: "SPGI", name: "S&P Global" },
  { symbol: "CRM", name: "Salesforce" },
  { symbol: "SNDK", name: "Sandisk" },
  { symbol: "SBAC", name: "SBA Communications" },
  { symbol: "SLB", name: "Schlumberger" },
  { symbol: "STX", name: "Seagate Technology" },
  { symbol: "SRE", name: "Sempra" },
  { symbol: "NOW", name: "ServiceNow" },
  { symbol: "SHW", name: "Sherwin-Williams" },
  { symbol: "SPG", name: "Simon Property Group" },
  { symbol: "SWKS", name: "Skyworks Solutions" },
  { symbol: "SJM", name: "J.M. Smucker Company (The)" },
  { symbol: "SW", name: "Smurfit Westrock" },
  { symbol: "SNA", name: "Snap-on" },
  { symbol: "SOLV", name: "Solventum" },
  { symbol: "SO", name: "Southern Company" },
  { symbol: "LUV", name: "Southwest Airlines" },
  { symbol: "SWK", name: "Stanley Black & Decker" },
  { symbol: "SBUX", name: "Starbucks" },
  { symbol: "STT", name: "State Street Corporation" },
  { symbol: "STLD", name: "Steel Dynamics" },
  { symbol: "STE", name: "Steris" },
  { symbol: "SYK", name: "Stryker Corporation" },
  { symbol: "SMCI", name: "Supermicro" },
  { symbol: "SYF", name: "Synchrony Financial" },
  { symbol: "SNPS", name: "Synopsys" },
  { symbol: "SYY", name: "Sysco" },
  { symbol: "TMUS", name: "T-Mobile US" },
  { symbol: "TROW", name: "T. Rowe Price" },
  { symbol: "TTWO", name: "Take-Two Interactive" },
  { symbol: "TPR", name: "Tapestry, Inc." },
  { symbol: "TRGP", name: "Targa Resources" },
  { symbol: "TGT", name: "Target Corporation" },
  { symbol: "TEL", name: "TE Connectivity" },
  { symbol: "TDY", name: "Teledyne Technologies" },
  { symbol: "TER", name: "Teradyne" },
  { symbol: "TSLA", name: "Tesla, Inc." },
  { symbol: "TXN", name: "Texas Instruments" },
  { symbol: "TPL", name: "Texas Pacific Land Corporation" },
  { symbol: "TXT", name: "Textron" },
  { symbol: "TMO", name: "Thermo Fisher Scientific" },
  { symbol: "TJX", name: "TJX Companies" },
  { symbol: "TKO", name: "TKO Group Holdings" },
  { symbol: "TTD", name: "Trade Desk (The)" },
  { symbol: "TSCO", name: "Tractor Supply" },
  { symbol: "TT", name: "Trane Technologies" },
  { symbol: "TDG", name: "TransDigm Group" },
  { symbol: "TRV", name: "Travelers Companies (The)" },
  { symbol: "TRMB", name: "Trimble Inc." },
  { symbol: "TFC", name: "Truist Financial" },
  { symbol: "TYL", name: "Tyler Technologies" },
  { symbol: "TSN", name: "Tyson Foods" },
  { symbol: "USB", name: "U.S. Bancorp" },
  { symbol: "UBER", name: "Uber" },
  { symbol: "UDR", name: "UDR, Inc." },
  { symbol: "ULTA", name: "Ulta Beauty" },
  { symbol: "UNP", name: "Union Pacific Corporation" },
  { symbol: "UAL", name: "United Airlines Holdings" },
  { symbol: "UPS", name: "United Parcel Service" },
  { symbol: "URI", name: "United Rentals" },
  { symbol: "UNH", name: "UnitedHealth Group" },
  { symbol: "UHS", name: "Universal Health Services" },
  { symbol: "VLO", name: "Valero Energy" },
  { symbol: "VTR", name: "Ventas,Real Estate" },
  { symbol: "VLTO", name: "Veralto" },
  { symbol: "VRSN", name: "Verisign" },
  { symbol: "VRSK", name: "Verisk Analytics" },
  { symbol: "VZ", name: "Verizon" },
  { symbol: "VRTX", name: "Vertex Pharmaceuticals" },
  { symbol: "VTRS", name: "Viatris" },
  { symbol: "VICI", name: "Vici Properties" },
  { symbol: "V", name: "Visa Inc." },
  { symbol: "VST", name: "Vistra Corp." },
  { symbol: "VMC", name: "Vulcan Materials Company" },
  { symbol: "WRB", name: "W. R. Berkley Corporation" },
  { symbol: "GWW", name: "W. W. Grainger" },
  { symbol: "WAB", name: "Wabtec" },
  { symbol: "WMT", name: "Walmart" },
  { symbol: "DIS", name: "Walt Disney Company (The)" },
  { symbol: "WBD", name: "Warner Bros. Discovery" },
  { symbol: "WM", name: "Waste Management" },
  { symbol: "WAT", name: "Waters Corporation" },
  { symbol: "WEC", name: "WEC Energy Group" },
  { symbol: "WFC", name: "Wells Fargo" },
  { symbol: "WELL", name: "Welltower,Real Estate" },
  { symbol: "WST", name: "West Pharmaceutical Services" },
  { symbol: "WDC", name: "Western Digital" },
  { symbol: "WY", name: "Weyerhaeuser" },
  { symbol: "WSM", name: "Williams-Sonoma, Inc." },
  { symbol: "WMB", name: "Williams Companies" },
  { symbol: "WTW", name: "Willis Towers Watson" },
  { symbol: "WDAY", name: "Workday, Inc." },
  { symbol: "WYNN", name: "Wynn Resorts" },
  { symbol: "XEL", name: "Xcel Energy" },
  { symbol: "XYL", name: "Xylem Inc." },
  { symbol: "YUM", name: "Yum! Brands" },
  { symbol: "ZBRA", name: "Zebra Technologies" },
  { symbol: "ZBH", name: "Zimmer Biomet" },
  { symbol: "ZTS", name: "Zoetis" },
];

/**
 * Big tech companies – major US and global technology stocks.
 * Includes those in S&P 500 plus additional high-profile tech names.
 */
export const BIG_TECH: { symbol: string; name: string }[] = [
  // Magnificent 7 / Mega-cap tech
  { symbol: "AAPL", name: "Apple Inc." },
  { symbol: "MSFT", name: "Microsoft" },
  { symbol: "GOOGL", name: "Alphabet (Google) Class A" },
  { symbol: "GOOG", name: "Alphabet (Google) Class C" },
  { symbol: "AMZN", name: "Amazon" },
  { symbol: "NVDA", name: "Nvidia" },
  { symbol: "META", name: "Meta Platforms (Facebook)" },
  { symbol: "TSLA", name: "Tesla" },
  // Semiconductors & hardware
  { symbol: "TSM", name: "Taiwan Semiconductor (TSMC)" },
  { symbol: "AVGO", name: "Broadcom" },
  { symbol: "AMD", name: "Advanced Micro Devices" },
  { symbol: "INTC", name: "Intel" },
  { symbol: "QCOM", name: "Qualcomm" },
  { symbol: "AMAT", name: "Applied Materials" },
  { symbol: "ASML", name: "ASML Holding" },
  { symbol: "LRCX", name: "Lam Research" },
  { symbol: "KLAC", name: "KLA Corporation" },
  { symbol: "MU", name: "Micron Technology" },
  { symbol: "MRVL", name: "Marvell Technology" },
  { symbol: "ARM", name: "Arm Holdings" },
  { symbol: "ON", name: "ON Semiconductor" },
  { symbol: "MPWR", name: "Monolithic Power Systems" },
  // Software & cloud
  { symbol: "CRM", name: "Salesforce" },
  { symbol: "ORCL", name: "Oracle" },
  { symbol: "ADBE", name: "Adobe" },
  { symbol: "NOW", name: "ServiceNow" },
  { symbol: "SNOW", name: "Snowflake" },
  { symbol: "DDOG", name: "Datadog" },
  { symbol: "CRWD", name: "CrowdStrike" },
  { symbol: "PANW", name: "Palo Alto Networks" },
  { symbol: "FTNT", name: "Fortinet" },
  { symbol: "ZS", name: "Zscaler" },
  { symbol: "NET", name: "Cloudflare" },
  { symbol: "MDB", name: "MongoDB" },
  { symbol: "TEAM", name: "Atlassian" },
  { symbol: "DOCU", name: "DocuSign" },
  { symbol: "OKTA", name: "Okta" },
  { symbol: "ZM", name: "Zoom Video" },
  { symbol: "TWLO", name: "Twilio" },
  { symbol: "HUBS", name: "HubSpot" },
  { symbol: "WDAY", name: "Workday" },
  { symbol: "INTU", name: "Intuit" },
  // Internet & consumer tech
  { symbol: "NFLX", name: "Netflix" },
  { symbol: "UBER", name: "Uber" },
  { symbol: "ABNB", name: "Airbnb" },
  { symbol: "SQ", name: "Block (Square)" },
  { symbol: "PYPL", name: "PayPal" },
  { symbol: "COIN", name: "Coinbase" },
  { symbol: "SPOT", name: "Spotify" },
  { symbol: "SNAP", name: "Snap" },
  { symbol: "PINS", name: "Pinterest" },
  { symbol: "ROKU", name: "Roku" },
  { symbol: "RBLX", name: "Roblox" },
  { symbol: "WIX", name: "Wix" },
  { symbol: "EBAY", name: "eBay" },
  // Enterprise & infrastructure
  { symbol: "CSCO", name: "Cisco" },
  { symbol: "IBM", name: "IBM" },
  { symbol: "CDNS", name: "Cadence Design Systems" },
  { symbol: "SNPS", name: "Synopsys" },
  { symbol: "ANET", name: "Arista Networks" },
  { symbol: "PLTR", name: "Palantir" },
  { symbol: "APP", name: "AppLovin" },
  { symbol: "AKAM", name: "Akamai Technologies" },
  { symbol: "CHTR", name: "Charter Communications" },
  { symbol: "CMCSA", name: "Comcast" },
  { symbol: "TMUS", name: "T-Mobile US" },
];

/**
 * Major international stocks (non-US exchanges, ADRs, global listings).
 * Symbols use yfinance format (US ADRs or exchange suffixes: .TW, .HK, .T, .L, etc.)
 */
export const INTERNATIONAL_STOCKS: { symbol: string; name: string }[] = [
  // Taiwan
  { symbol: "TSM", name: "Taiwan Semiconductor (TSMC)" },
  { symbol: "2330.TW", name: "Taiwan Semiconductor (Taiwan)" },
  { symbol: "2454.TW", name: "MediaTek (Taiwan)" },
  { symbol: "2317.TW", name: "Hon Hai / Foxconn (Taiwan)" },
  // Japan
  { symbol: "TM", name: "Toyota Motor (ADR)" },
  { symbol: "7203.T", name: "Toyota Motor (Japan)" },
  { symbol: "SONY", name: "Sony Group (ADR)" },
  { symbol: "6758.T", name: "Sony Group (Japan)" },
  { symbol: "HMC", name: "Honda Motor (ADR)" },
  { symbol: "7267.T", name: "Honda Motor (Japan)" },
  { symbol: "MUFG", name: "Mitsubishi UFJ Financial (ADR)" },
  { symbol: "8306.T", name: "Mitsubishi UFJ Financial (Japan)" },
  { symbol: "NTT", name: "Nippon Telegraph & Telephone (ADR)" },
  { symbol: "9432.T", name: "Nippon Telegraph & Telephone (Japan)" },
  { symbol: "9984.T", name: "SoftBank Group (Japan)" },
  { symbol: "6752.T", name: "Panasonic (Japan)" },
  { symbol: "6861.T", name: "Keyence (Japan)" },
  { symbol: "6902.T", name: "Denso (Japan)" },
  // China / Hong Kong
  { symbol: "BABA", name: "Alibaba Group (ADR)" },
  { symbol: "9988.HK", name: "Alibaba Group (Hong Kong)" },
  { symbol: "PDD", name: "Pinduoduo (ADR)" },
  { symbol: "TCEHY", name: "Tencent Holdings (ADR)" },
  { symbol: "0700.HK", name: "Tencent Holdings (Hong Kong)" },
  { symbol: "JD", name: "JD.com (ADR)" },
  { symbol: "9618.HK", name: "JD.com (Hong Kong)" },
  { symbol: "NIO", name: "NIO Inc. (ADR)" },
  { symbol: "LI", name: "Li Auto (ADR)" },
  { symbol: "XPEV", name: "XPeng (ADR)" },
  { symbol: "BIDU", name: "Baidu (ADR)" },
  { symbol: "3690.HK", name: "Meituan (Hong Kong)" },
  // South Korea
  { symbol: "005930.KS", name: "Samsung Electronics (Korea)" },
  { symbol: "000660.KS", name: "SK Hynix (Korea)" },
  { symbol: "051910.KS", name: "LG Chem (Korea)" },
  { symbol: "035420.KS", name: "NAVER (Korea)" },
  { symbol: "035720.KS", name: "Kakao (Korea)" },
  // Europe
  { symbol: "ASML", name: "ASML Holding (Netherlands)" },
  { symbol: "SAP", name: "SAP SE (Germany)" },
  { symbol: "SAP.DE", name: "SAP SE (Xetra)" },
  { symbol: "LVMUY", name: "LVMH Moët Hennessy (ADR)" },
  { symbol: "MC.PA", name: "LVMH (Paris)" },
  { symbol: "NSRGY", name: "Nestlé (ADR)" },
  { symbol: "NESN.SW", name: "Nestlé (Switzerland)" },
  { symbol: "AZN", name: "AstraZeneca (ADR)" },
  { symbol: "AZN.L", name: "AstraZeneca (London)" },
  { symbol: "SHEL", name: "Shell plc (ADR)" },
  { symbol: "SHEL.L", name: "Shell plc (London)" },
  { symbol: "BP", name: "BP plc (ADR)" },
  { symbol: "BP.L", name: "BP plc (London)" },
  { symbol: "UL", name: "Unilever (ADR)" },
  { symbol: "ULVR.L", name: "Unilever (London)" },
  { symbol: "SIEGY", name: "Siemens (ADR)" },
  { symbol: "SIE.DE", name: "Siemens (Xetra)" },
  { symbol: "OR.PA", name: "L'Oréal (Paris)" },
  { symbol: "SAN", name: "Santander (ADR)" },
  { symbol: "SAN.MC", name: "Santander (Madrid)" },
  { symbol: "DB", name: "Deutsche Bank (ADR)" },
  { symbol: "DBK.DE", name: "Deutsche Bank (Xetra)" },
  { symbol: "NVO", name: "Novo Nordisk (ADR)" },
  { symbol: "NOVO-B.CO", name: "Novo Nordisk (Copenhagen)" },
  { symbol: "ABBN.SW", name: "ABB (Switzerland)" },
  { symbol: "ROG.SW", name: "Roche Holding (Switzerland)" },
  { symbol: "NOVN.SW", name: "Novartis (Switzerland)" },
  // Canada
  { symbol: "SHOP", name: "Shopify (Canada)" },
  { symbol: "SHOP.TO", name: "Shopify (Toronto)" },
  { symbol: "RY", name: "Royal Bank of Canada (ADR)" },
  { symbol: "RY.TO", name: "Royal Bank of Canada (Toronto)" },
  { symbol: "TD", name: "Toronto-Dominion Bank (ADR)" },
  { symbol: "TD.TO", name: "Toronto-Dominion Bank (Toronto)" },
  { symbol: "BMO", name: "Bank of Montreal (ADR)" },
  { symbol: "CNR.TO", name: "Canadian National Railway (Toronto)" },
  { symbol: "CP.TO", name: "Canadian Pacific Kansas City (Toronto)" },
  // Australia
  { symbol: "BHP", name: "BHP Group (ADR)" },
  { symbol: "BHP.AX", name: "BHP Group (Australia)" },
  { symbol: "RIO", name: "Rio Tinto (ADR)" },
  { symbol: "RIO.AX", name: "Rio Tinto (Australia)" },
  { symbol: "CBA.AX", name: "Commonwealth Bank (Australia)" },
  { symbol: "NAB.AX", name: "National Australia Bank (Australia)" },
  // India
  { symbol: "INFY", name: "Infosys (ADR)" },
  { symbol: "INFY.NS", name: "Infosys (NSE)" },
  { symbol: "WIT", name: "Wipro (ADR)" },
  { symbol: "TCS.NS", name: "Tata Consultancy Services (NSE)" },
  { symbol: "RELIANCE.NS", name: "Reliance Industries (NSE)" },
];

/**
 * Top 200 ETFs by AUM for autocomplete.
 * Source: ETFdb.com (top 100) + major ETFs by assets/trading volume
 */
export const ETFS: { symbol: string; name: string }[] = [
  { symbol: "VOO", name: "Vanguard S&P 500 ETF" },
  { symbol: "IVV", name: "iShares Core S&P 500 ETF" },
  { symbol: "SPY", name: "SPDR S&P 500 ETF" },
  { symbol: "VTI", name: "Vanguard Total Stock Market ETF" },
  { symbol: "QQQ", name: "Invesco QQQ Trust" },
  { symbol: "VEA", name: "Vanguard FTSE Developed Markets ETF" },
  { symbol: "VUG", name: "Vanguard Growth ETF" },
  { symbol: "GLD", name: "SPDR Gold Shares" },
  { symbol: "IEFA", name: "iShares Core MSCI EAFE ETF" },
  { symbol: "VTV", name: "Vanguard Value ETF" },
  { symbol: "BND", name: "Vanguard Total Bond Market ETF" },
  { symbol: "IEMG", name: "iShares Core MSCI Emerging Markets ETF" },
  { symbol: "AGG", name: "iShares Core U.S. Aggregate Bond ETF" },
  { symbol: "VXUS", name: "Vanguard Total International Stock ETF" },
  { symbol: "IWF", name: "iShares Russell 1000 Growth ETF" },
  { symbol: "VWO", name: "Vanguard FTSE Emerging Markets ETF" },
  { symbol: "VGT", name: "Vanguard Information Technology ETF" },
  { symbol: "IJH", name: "iShares Core S&P Mid-Cap ETF" },
  { symbol: "VIG", name: "Vanguard Dividend Appreciation ETF" },
  { symbol: "VO", name: "Vanguard Mid-Cap ETF" },
  { symbol: "IJR", name: "iShares Core S&P Small-Cap ETF" },
  { symbol: "XLK", name: "Technology Select Sector SPDR ETF" },
  { symbol: "RSP", name: "Invesco S&P 500 Equal Weight ETF" },
  { symbol: "SCHD", name: "Schwab US Dividend Equity ETF" },
  { symbol: "IAU", name: "iShares Gold Trust" },
  { symbol: "ITOT", name: "iShares Core S&P Total U.S. Stock Market ETF" },
  { symbol: "SGOV", name: "iShares 0-3 Month Treasury Bond ETF" },
  { symbol: "BNDX", name: "Vanguard Total International Bond ETF" },
  { symbol: "VYM", name: "Vanguard High Dividend Yield ETF" },
  { symbol: "EFA", name: "iShares MSCI EAFE ETF" },
  { symbol: "VB", name: "Vanguard Small Cap ETF" },
  { symbol: "QQQM", name: "Invesco NASDAQ 100 ETF" },
  { symbol: "IWM", name: "iShares Russell 2000 ETF" },
  { symbol: "IWD", name: "iShares Russell 1000 Value ETF" },
  { symbol: "VCIT", name: "Vanguard Intermediate-Term Corporate Bond ETF" },
  { symbol: "IVW", name: "iShares S&P 500 Growth ETF" },
  { symbol: "VT", name: "Vanguard Total World Stock ETF" },
  { symbol: "SCHX", name: "Schwab U.S. Large-Cap ETF" },
  { symbol: "VEU", name: "Vanguard FTSE All-World ex-US ETF" },
  { symbol: "SCHF", name: "Schwab International Equity ETF" },
  { symbol: "IBIT", name: "iShares Bitcoin Trust ETF" },
  { symbol: "IXUS", name: "iShares Core MSCI Total International Stock ETF" },
  { symbol: "SCHG", name: "Schwab U.S. Large-Cap Growth ETF" },
  { symbol: "QUAL", name: "iShares MSCI USA Quality Factor ETF" },
  { symbol: "IVE", name: "iShares S&P 500 Value ETF" },
  { symbol: "IEF", name: "iShares 7-10 Year Treasury Bond ETF" },
  { symbol: "IWR", name: "iShares Russell Midcap ETF" },
  { symbol: "VV", name: "Vanguard Large Cap ETF" },
  { symbol: "XLF", name: "Financial Select Sector SPDR ETF" },
  { symbol: "IWB", name: "iShares Russell 1000 ETF" },
  { symbol: "SMH", name: "VanEck Semiconductor ETF" },
  { symbol: "BIL", name: "SPDR Bloomberg 1-3 Month T-Bill ETF" },
  { symbol: "JEPI", name: "JPMorgan Equity Premium Income ETF" },
  { symbol: "TLT", name: "iShares 20+ Year Treasury Bond ETF" },
  { symbol: "BSV", name: "Vanguard Short-Term Bond ETF" },
  { symbol: "SLV", name: "iShares Silver Trust" },
  { symbol: "DIA", name: "SPDR Dow Jones Industrial Average ETF" },
  { symbol: "MUB", name: "iShares National Muni Bond ETF" },
  { symbol: "VTEB", name: "Vanguard Tax-Exempt Bond ETF" },
  { symbol: "VCSH", name: "Vanguard Short-Term Corporate Bond ETF" },
  { symbol: "XLV", name: "Health Care Select Sector SPDR ETF" },
  { symbol: "VGIT", name: "Vanguard Intermediate-Term Treasury ETF" },
  { symbol: "XLE", name: "Energy Select Sector SPDR ETF" },
  { symbol: "SCHB", name: "Schwab U.S. Broad Market ETF" },
  { symbol: "DGRO", name: "iShares Core Dividend Growth ETF" },
  { symbol: "JPST", name: "JPMorgan Ultra-Short Income ETF" },
  { symbol: "VNQ", name: "Vanguard Real Estate ETF" },
  { symbol: "IUSB", name: "iShares Core Total USD Bond Market ETF" },
  { symbol: "GOVT", name: "iShares U.S. Treasury Bond ETF" },
  { symbol: "JEPQ", name: "JPMorgan NASDAQ Equity Premium Income ETF" },
  { symbol: "VBR", name: "Vanguard Small Cap Value ETF" },
  { symbol: "GDX", name: "VanEck Gold Miners ETF" },
  { symbol: "LQD", name: "iShares iBoxx Investment Grade Corporate Bond ETF" },
  { symbol: "VGK", name: "Vanguard FTSE Europe ETF" },
  { symbol: "EFV", name: "iShares MSCI EAFE Value ETF" },
  { symbol: "MGK", name: "Vanguard Mega Cap Growth ETF" },
  { symbol: "XLI", name: "Industrial Select Sector SPDR ETF" },
  { symbol: "OEF", name: "iShares S&P 100 ETF" },
  { symbol: "EEM", name: "iShares MSCI Emerging Markets ETF" },
  { symbol: "VGSH", name: "Vanguard Short-Term Treasury ETF" },
  { symbol: "BIV", name: "Vanguard Intermediate-Term Bond ETF" },
  { symbol: "ACWI", name: "iShares MSCI ACWI ETF" },
  { symbol: "TQQQ", name: "ProShares UltraPro QQQ" },
  { symbol: "USHY", name: "iShares Broad USD High Yield Corporate Bond ETF" },
  { symbol: "XLC", name: "Communication Services Select Sector SPDR ETF" },
  { symbol: "VXF", name: "Vanguard Extended Market ETF" },
  { symbol: "FBND", name: "Fidelity Total Bond ETF" },
  { symbol: "HYG", name: "iShares iBoxx High Yield Corporate Bond ETF" },
  { symbol: "ARKK", name: "ARK Innovation ETF" },
  { symbol: "SOXX", name: "iShares Semiconductor ETF" },
  { symbol: "XLY", name: "Consumer Discretionary Select Sector SPDR ETF" },
  { symbol: "XLP", name: "Consumer Staples Select Sector SPDR ETF" },
  { symbol: "XLU", name: "Utilities Select Sector SPDR ETF" },
  { symbol: "XLB", name: "Materials Select Sector SPDR ETF" },
  { symbol: "KRE", name: "SPDR S&P Regional Banking ETF" },
  { symbol: "XBI", name: "SPDR S&P Biotech ETF" },
  { symbol: "SQQQ", name: "ProShares UltraShort QQQ" },
  { symbol: "UPRO", name: "ProShares UltraPro S&P 500" },
  { symbol: "EMB", name: "iShares J.P. Morgan USD Emerging Markets Bond ETF" },
  { symbol: "FXI", name: "iShares China Large-Cap ETF" },
  { symbol: "EWJ", name: "iShares MSCI Japan ETF" },
  { symbol: "VHT", name: "Vanguard Health Care ETF" },
  { symbol: "IGV", name: "iShares Expanded Tech-Software Sector ETF" },
  { symbol: "XLRE", name: "Real Estate Select Sector SPDR ETF" },
  { symbol: "VDE", name: "Vanguard Energy ETF" },
  { symbol: "VFH", name: "Vanguard Financials ETF" },
  { symbol: "BNDW", name: "Vanguard Total World Bond ETF" },
  { symbol: "AVUV", name: "Avantis U.S. Small Cap Value ETF" },
  { symbol: "AVDV", name: "Avantis International Small Cap Value ETF" },
  { symbol: "AVEM", name: "Avantis Emerging Markets Equity ETF" },
  { symbol: "DFAU", name: "Dimensional U.S. Core Equity Market ETF" },
  { symbol: "DFAX", name: "Dimensional World ex U.S. Core Equity ETF" },
  { symbol: "DFEM", name: "Dimensional Emerging Markets Core Equity ETF" },
  { symbol: "VIOV", name: "Vanguard S&P Small-Cap 600 Value ETF" },
  { symbol: "VIOG", name: "Vanguard S&P Small-Cap 600 Growth ETF" },
  { symbol: "VOT", name: "Vanguard Mid-Cap Growth ETF" },
  { symbol: "VOE", name: "Vanguard Mid-Cap Value ETF" },
  { symbol: "VCR", name: "Vanguard Consumer Discretionary ETF" },
  { symbol: "VDC", name: "Vanguard Consumer Staples ETF" },
  { symbol: "VAW", name: "Vanguard Materials ETF" },
  { symbol: "VIS", name: "Vanguard Industrials ETF" },
  { symbol: "VOX", name: "Vanguard Communication Services ETF" },
  { symbol: "VPU", name: "Vanguard Utilities ETF" },
  { symbol: "BKLN", name: "Invesco Senior Loan ETF" },
  { symbol: "PFF", name: "iShares Preferred and Income Securities ETF" },
  { symbol: "TIP", name: "iShares TIPS Bond ETF" },
  { symbol: "SHY", name: "iShares 1-3 Year Treasury Bond ETF" },
  { symbol: "SHV", name: "iShares Short Treasury Bond ETF" },
  { symbol: "FLOT", name: "iShares Floating Rate Bond ETF" },
  { symbol: "VGLT", name: "Vanguard Long-Term Treasury ETF" },
  { symbol: "EDV", name: "Vanguard Extended Duration Treasury ETF" },
  { symbol: "VCLT", name: "Vanguard Long-Term Corporate Bond ETF" },
  { symbol: "VWOB", name: "Vanguard Emerging Markets Government Bond ETF" },
  { symbol: "HDV", name: "iShares Core High Dividend ETF" },
  { symbol: "DVY", name: "iShares Select Dividend ETF" },
  { symbol: "SDY", name: "SPDR S&P Dividend ETF" },
  { symbol: "NOBL", name: "ProShares S&P 500 Dividend Aristocrats ETF" },
  { symbol: "SPHD", name: "Invesco S&P 500 High Dividend Low Volatility ETF" },
  { symbol: "SCHY", name: "Schwab International Dividend Equity ETF" },
  { symbol: "VYMI", name: "Vanguard International High Dividend Yield ETF" },
  { symbol: "IDV", name: "iShares International Select Dividend ETF" },
  { symbol: "VIGI", name: "Vanguard International Dividend Appreciation ETF" },
  { symbol: "AOR", name: "iShares Core Growth Allocation ETF" },
  { symbol: "AOA", name: "iShares Core Aggressive Growth Allocation ETF" },
  { symbol: "AOM", name: "iShares Core Moderate Growth Allocation ETF" },
  { symbol: "AOK", name: "iShares Core Conservative Allocation ETF" },
  { symbol: "NTSX", name: "WisdomTree U.S. Efficient Core Fund" },
  { symbol: "NTSI", name: "WisdomTree International Efficient Core Fund" },
  { symbol: "NTSE", name: "WisdomTree Emerging Markets Efficient Core Fund" },
  { symbol: "AVGE", name: "Avantis All Equity Markets Value ETF" },
  { symbol: "GLDM", name: "SPDR Gold MiniShares Trust" },
  { symbol: "IAUM", name: "iShares Gold Trust Micro" },
  { symbol: "SGOL", name: "Aberdeen Standard Physical Gold Shares ETF" },
  { symbol: "SIVR", name: "Aberdeen Standard Physical Silver Shares ETF" },
  { symbol: "PALL", name: "Aberdeen Standard Physical Palladium Shares ETF" },
  { symbol: "PPLT", name: "Aberdeen Standard Physical Platinum Shares ETF" },
  { symbol: "USO", name: "United States Oil Fund" },
  { symbol: "BNO", name: "Brent Oil Fund" },
  { symbol: "UNG", name: "United States Natural Gas Fund" },
  { symbol: "DBA", name: "Invesco DB Agriculture Fund" },
  { symbol: "DBC", name: "Invesco DB Commodity Index Tracking Fund" },
  { symbol: "PDBC", name: "Invesco Optimum Yield Diversified Commodity Fund" },
  { symbol: "GSG", name: "iShares S&P GSCI Commodity-Indexed Trust" },
  { symbol: "DJP", name: "iShares Bloomberg Commodity Index Trust" },
  { symbol: "COMT", name: "iShares GSCI Commodity Dynamic Roll Strategy ETF" },
  { symbol: "USCI", name: "United States Commodity Index Fund" },
  { symbol: "CMDT", name: "PIMCO Commodity Strategy Fund" },
  { symbol: "FTGC", name: "First Trust Global Tactical Commodity Strategy Fund" },
  { symbol: "QQQJ", name: "Invesco NASDAQ Next Gen 100 ETF" },
  { symbol: "SOXL", name: "Direxion Daily Semiconductor Bull 3X Shares" },
  { symbol: "TECL", name: "Direxion Daily Technology Bull 3X Shares" },
  { symbol: "SPXL", name: "Direxion Daily S&P 500 Bull 3X Shares" },
  { symbol: "LABU", name: "Direxion Daily S&P Biotech Bull 3X Shares" },
  { symbol: "SSO", name: "ProShares Ultra S&P 500" },
  { symbol: "QLD", name: "ProShares Ultra QQQ" },
  { symbol: "ROM", name: "ProShares Ultra Technology" },
  { symbol: "UYG", name: "ProShares Ultra Financials" },
  { symbol: "RXL", name: "ProShares Ultra Health Care" },
  { symbol: "UXI", name: "ProShares Ultra Industrials" },
  { symbol: "UPW", name: "ProShares Ultra Utilities" },
  { symbol: "URE", name: "ProShares Ultra Real Estate" },
  { symbol: "UCO", name: "ProShares Ultra Bloomberg Crude Oil" },
  { symbol: "BOIL", name: "ProShares Ultra Bloomberg Natural Gas" },
  { symbol: "AGQ", name: "ProShares Ultra Silver" },
  { symbol: "UGL", name: "ProShares Ultra Gold" },
  { symbol: "TMF", name: "Direxion Daily 20+ Year Treasury Bull 3X Shares" },
  { symbol: "TMV", name: "Direxion Daily 20+ Year Treasury Bear 3X Shares" },
  { symbol: "TYD", name: "Direxion Daily 7-10 Year Treasury Bull 3X Shares" },
  { symbol: "TYO", name: "Direxion Daily 7-10 Year Treasury Bear 3X Shares" },
  { symbol: "UST", name: "ProShares Ultra 7-10 Year Treasury" },
  { symbol: "PST", name: "ProShares UltraShort 7-10 Year Treasury" },
  { symbol: "SH", name: "ProShares Short S&P 500" },
  { symbol: "PSQ", name: "ProShares Short QQQ" },
  { symbol: "DOG", name: "ProShares Short Dow30" },
  { symbol: "RWM", name: "ProShares Short Russell2000" },
  { symbol: "SDS", name: "ProShares UltraShort S&P 500" },
  { symbol: "QID", name: "ProShares UltraShort QQQ" },
  { symbol: "DXD", name: "ProShares UltraShort Dow30" },
  { symbol: "TWM", name: "ProShares UltraShort Russell2000" },
  { symbol: "TBT", name: "ProShares UltraShort 20+ Year Treasury" },
  { symbol: "VXX", name: "iPath S&P 500 VIX Short-Term Futures ETN" },
  { symbol: "UVXY", name: "ProShares Ultra VIX Short-Term Futures" },
  { symbol: "SVXY", name: "ProShares Short VIX Short-Term Futures" },
  { symbol: "VIXY", name: "ProShares VIX Short-Term Futures" },
  { symbol: "ZROZ", name: "PIMCO 25+ Year Zero Coupon U.S. Treasury ETF" },
  { symbol: "BILS", name: "SPDR Bloomberg 3-12 Month T-Bill ETF" },
  { symbol: "TFLO", name: "iShares Treasury Floating Rate Bond ETF" },
  { symbol: "USFR", name: "WisdomTree Floating Rate Treasury Fund" },
  { symbol: "FLTR", name: "VanEck Investment Grade Floating Rate ETF" },
];

const MAX_SUGGESTIONS = 10;

const SEARCHABLES = [...STOCKS, ...BIG_TECH, ...INTERNATIONAL_STOCKS, ...ETFS];

export function getCompanyName(symbol: string): string | undefined {
  const s = symbol?.trim().toUpperCase();
  if (!s) return undefined;
  return SEARCHABLES.find((x) => x.symbol.toUpperCase() === s)?.name;
}

export function searchStocks(query: string): { symbol: string; name: string }[] {
  const q = query.trim().toLowerCase();
  if (!q) return [];
  const matches = SEARCHABLES.filter(
    (s) =>
      s.symbol.toLowerCase().includes(q) ||
      s.name.toLowerCase().includes(q)
  );
  // Deduplicate by symbol (first occurrence wins)
  const seen = new Set<string>();
  const deduped = matches.filter((m) => {
    const key = m.symbol.toUpperCase();
    if (seen.has(key)) return false;
    seen.add(key);
    return true;
  });
  // Sort by relevance: exact symbol > name starts with > symbol starts with > name contains > symbol contains
  deduped.sort((a, b) => {
    const score = (s: { symbol: string; name: string }): number => {
      const sym = s.symbol.toLowerCase();
      const name = s.name.toLowerCase();
      if (sym === q) return 0;
      if (name.startsWith(q)) return 1;
      if (sym.startsWith(q)) return 2;
      if (name.includes(q)) return 3;
      return 4;
    };
    return score(a) - score(b);
  });
  return deduped.slice(0, MAX_SUGGESTIONS);
}
